// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using coffeeshop.Data;

#nullable disable

namespace CoffeeShop.Migrations
{
    [DbContext(typeof(CoffeeshopDbContext))]
    [Migration("20260526031915_UpdateProductImages")]
    partial class UpdateProductImages
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CoffeeShop.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsTrendingProduct")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Classic American coffee with smooth taste.",
                            ImageUrl = "https://images.unsplash.com/photo-1509042239860-f550ce710b93?w=500",
                            IsTrendingProduct = true,
                            Name = "America",
                            Price = 25m
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Strong Vietnamese coffee with condensed milk.",
                            ImageUrl = "https://images.unsplash.com/photo-1514432324607-a09d9b4aefdd?w=500",
                            IsTrendingProduct = true,
                            Name = "Vietnam",
                            Price = 20m
                        },
                        new
                        {
                            Id = 3,
                            Detail = "British style tea-infused coffee blend.",
                            ImageUrl = "https://images.unsplash.com/photo-1461023058943-07fcbe16d735?w=500",
                            IsTrendingProduct = false,
                            Name = "United Kingdom",
                            Price = 15m
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Spiced Indian coffee with cardamom.",
                            ImageUrl = "https://images.unsplash.com/photo-1495474472287-4d71bcdd2085?w=500",
                            IsTrendingProduct = false,
                            Name = "India",
                            Price = 15m
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Bold Russian black coffee.",
                            ImageUrl = "https://images.unsplash.com/photo-1497515114629-f71d768fd07c?w=500",
                            IsTrendingProduct = true,
                            Name = "Russian",
                            Price = 25m
                        },
                        new
                        {
                            Id = 6,
                            Detail = "French press coffee with rich aroma.",
                            ImageUrl = "https://images.unsplash.com/photo-1504630083234-14187a9df0f5?w=500",
                            IsTrendingProduct = false,
                            Name = "France",
                            Price = 35m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
